myproject/blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('aboutme/', views.aboutMe, name='aboutme'),
    path('techtips/', views.techtips, name='techtips'),
    path('<int:pk>/detail/', views.detail, name='detail'),
    path('archive/', views.archive, name='archive'),
    path('init/', views.boot, name='init'),
    path('comment/<int:blog_id>', views.comment, name='comment'),

]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('blog.urls')),
    path('blog/', include('blog.urls')),
    path('polls/', include('polls.urls')),
    path('admin/', admin.site.urls),
]

myproject/polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
	path('', views.IndexView.as_view(), name='index'),
	path('<int:pk>/', views.DetailView.as_view(), name='detail'),
	path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
	path('<int:question_id>/vote/', views.vote, name = 'vote'),
]

myproject/blog/models.py
from django.db import models
from django.utils import timezone

class Blog(models.Model):
    title = models.CharField(max_length=55)
    author_name = models.CharField(max_length=25)
    content = models.CharField(max_length=2750)
    pub_date = models.DateTimeField('date published')
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __str__(self):
        return self.title


class Comment(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=25)
    email = models.CharField(max_length=30)
    content = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return "Comment no " + str(self.id)

myproject/polls/models.py
from django.db import models
from django.utils import timezone

class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	def was_published_recently(self):
		return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __str__(self):
		return self.choice_text

myproject/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.template import loader
from django.urls import reverse
from django.views import generic
from .models import Blog, Comment
from time import strftime
from random import randint
from django.http import HttpResponseRedirect
from .lipsum import LOREMIPSUM
from django.utils import timezone

def comment(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    blog.comment_set.create(nickname=request.POST['nickname'],
                            email=request.POST['email'],
                            content=request.POST['content'],
                            pub_date=timezone.now())

    return HttpResponseRedirect(reverse('blog:detail', args=(blog_id,)))
def boot(request):
    #do all the autofill stuff here
    Blog.objects.all().delete()

    for b in range(6):
        sb = str(b)
        blog = Blog(title = "Blog post #" + sb,
        author_name = "A Person",
        content = LOREMIPSUM[randint(0,200):randint(200,len(LOREMIPSUM))],
        pub_date = timezone.now())
 
        blog.save()
        
        for c in range(b + 1):
            sc = str(c)
            blog.comment_set.create(nickname = "commentguy",

                      email = "commentguy@fakemail.com",
                      content = LOREMIPSUM[0:randint(100,200)],
                      pub_date = timezone.now())  

    return HttpResponseRedirect(reverse('blog:index'))

def index(request):
    recent_blogs = Blog.objects.order_by('-pub_date')[:3]

    d = {'time':strftime('%c'),
        'recent_blogs':recent_blogs}
    return render(request, 'blog/templates/index.html', d)

def detail(request, pk):
    blog = Blog.objects.get(id=pk)
    comments = Comment.objects.order_by('-pub_date').filter(blog_id=pk)
    d = {'comments': comments, 
         'blog':blog,
        'time':strftime('%c'),
    }
    return render(request, 'blog/templates/detail.html', d)

def aboutMe(request):
    return render(request, 'blog/templates/aboutme.html', {'time':strftime('%c'),})

def techtips(request):
    return render(request, 'blog/templates/techtips.html', {'time':strftime('%c'),})

def archive(request):
    blogs = Blog.objects.order_by('-pub_date')
    d = {'time':strftime('%c'),
        'blogs':blogs}
    return render(request, 'blog/templates/archive.html', d)

myproject/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.views import generic
from django.template import loader
from django.urls import reverse
from .models import Question

class IndexView(generic.ListView):
	template_name = 'polls/index.html'
	context_object_name = 'latest_question_list'

	def get_queryset(self):
		return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
	model = Question
	template_name = 'polls/detail.html'

class ResultsView(generic.DetailView):
	model = Question
	template_name = 'polls/results.html'


def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'polls/detail.html', {
			'question': question,
			'error_message': "You didn't select a choice.",
		})
	else:
		selected_choice.votes +=1
		selected_choice.save()

		return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

myproject/blog/templates/blog/templates/aboutme.html
<!DOCTYPE HTML>

<head>
	<title> About Me </title>
{% load static %}
	<link href="{% static 'blog/static/style.css' %}" rel="stylesheet" title="Main style">
</head>

<body>
<header> THE BLOG
<nav>
	<a href="{% url 'blog:index' %}"> Home </a> |
	<a href="{% url 'blog:aboutme' %}"> About Me </a> |
	<a href="{% url 'blog:techtips' %}"> Tech Tips </a>|
        <a href="{% url 'blog:archive' %}"> Archive </a>
</nav>
</header>


<div class="flex-box">
<div class="main">
<article>
<h1> About Me</h1>
<img src="https://thumb1.shutterstock.com/display_pic_with_logo/101595/492562780/stock-photo-handsome-young-man-on-grey-background-looking-at-camera-portrait-of-laughing-young-man-with-hands-492562780.jpg" alt="Picture of a guy">

<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p>
</article>
</div>

<aside class="aside">
	<img src="https://thumb1.shutterstock.com/display_pic_with_logo/4571494/649452289/stock-photo-an-extreme-sportsman-jumps-on-a-rope-from-a-great-height-ropejumping-649452289.jpg" alt="Bungee jumping">
	<img src="https://thumb1.shutterstock.com/display_pic_with_logo/340054/145156063/stock-photo-a-picture-of-a-biker-making-a-stunt-and-jumps-in-the-air-145156063.jpg" alt="Dirt biking">
	<img src="{% static 'blog/static/dumb.jpg' %}" alt="Kite Boarding">

</aside>
</div>

<footer>
Ryan Ferguson--{{ time }}
</footer>


</body>

myproject/blog/templates/blog/templates/archive.html
<!DOCTYPE html>
<html lang="zxx">
<head>
{% load static %}
	<link href="{% static 'blog/static/style.css' %}" rel="stylesheet" title="Main style">
<title> Archive </title>
</head>



<body>
<header> THE BLOG
<nav>
	<a href="{% url 'blog:index' %}"> Home </a> |
	<a href="{% url 'blog:aboutme' %}"> About Me </a> |
	<a href="{% url 'blog:techtips' %}"> Tech Tips </a>|
        <a href="{% url 'blog:archive' %}"> Archive </a>
</nav>
</header>
<div class="flex-box">
<div class="main">
<main class="main">
<h1> The Blog Archive </h1>


{% for blog in blogs %}
<h2><a href="{% url 'blog:detail' blog.id %}">{{ blog.title }} </a> </h2>
<p class="sub"> {{ blog.author_name }} {{ blog.pub_date }} </p>
<p> {{ blog.content |truncatewords:200}} </p>
<p class="sub"> {{blog.comment_set.count}} comments </p>

{% endfor %}


</main>
</div>
<div class="aside">
<aside class="aside">
	<p> Here are the links to the other pages </p>
	<p><a href="{% url 'blog:aboutme' %}">About Me</a></p>
	<p><a href="{% url 'blog:techtips' %}">Tech Tips</a></p>
	
</aside>
</div>
</div>
<footer>
Ryan Ferguson--{{ time }}
</footer>

</body>
</html>

myproject/blog/templates/blog/templates/detail.html
<DOCTYPE! HTML>
<html>
<head>
{% load static %}
<link href="{% static 'blog/static/style.css' %}" rel="stylesheet">
<title>{{blog.title}}</title>

</head>
<body>
<header> THE BLOG
<nav>
	<a href="{% url 'blog:index' %}"> Home </a> |
	<a href="{% url 'blog:aboutme' %}"> About Me </a> |
	<a href="{% url 'blog:techtips' %}"> Tech Tips </a>|
        <a href="{% url 'blog:archive' %}"> Archive </a>
</nav>
</header>

<div class="flex-box">
<div class="main">
<main class="main">
<h2> {{blog.title}}</h2>
<p class="sub"> {{blog.author_name}} {{blog.pub_date}} </p>

<p> {{blog.content}}</p>
</br>
<h2> Comments </h2>
<form action="{%url 'blog:comment' blog.id %}" method="post" id=commentform">
{% csrf_token %}
<p> Nickname </p>
<input type="text" name="nickname" id="nickname">
<p> Email </p>
<input type="text" name="email" id="email">
<p> Comment </p>
<input type="text" name="content" id="content" size="85"></br>
<input type="submit" value="Submit">
</form>
<hr>

{% for comment in comments %}
<p class="nickname"> {{comment.nickname}}</p>
<p> {{comment.content}} </p>
<p class="sub">{{comment.email}}--{{comment.pub_date}} </p>
<hr>
</br>
{% endfor %}

</main>
</div>
<div class="aside">
<aside class="aside">
	<p> Here are the links to the other pages </p>
	<p><a href="{% url 'blog:aboutme' %}">About Me</a></p>
	<p><a href="{% url 'blog:techtips' %}">Tech Tips</a></p>
	
</aside>
</div>
</div>
<footer>
Ryan Ferguson--{{ time }}
</footer>


</body>
</html>

myproject/blog/templates/blog/templates/index.html
<!DOCTYPE html>
<html lang="zxx">
<head>
	<title>The Blog</title>
{% load static %}
	<link href="{% static 'blog/static/style.css' %}" rel="stylesheet" title="Main style">

</head>



<body>
<header> THE BLOG
<nav>
	<a href="{% url 'blog:index' %}"> Home </a> |
	<a href="{% url 'blog:aboutme' %}"> About Me </a> |
	<a href="{% url 'blog:techtips' %}"> Tech Tips </a> |
        <a href="{% url 'blog:archive' %}"> Archive </a>
</nav>
</header>
<div class="flex-box">
<div class="main">
<main class="main">
<h1> The Blog Main Page </h1>

<p>I used the mozilla css guide for most of this. The images were marked for reuse</p>
{% for blog in recent_blogs %}
<h2><a href="{% url 'blog:detail' blog.id %}">{{ blog.title }} </a> </h2>
<p class="sub"> {{ blog.author_name }} {{ blog.pub_date }} </p>
<p> {{ blog.content |truncatewords:200}} </p>
<p class="sub"> {{blog.comment_set.count}} comments </p>

{% endfor %}


</main>
</div>
<div class="aside">
<aside class="aside">
	<p> Here are the links to the other pages </p>
	<p><a href="{% url 'blog:aboutme' %}">About Me</a></p>
	<p><a href="{% url 'blog:techtips' %}">Tech Tips</a></p>
	
</aside>
</div>
</div>
<footer>
Ryan Ferguson--{{ time }}
</footer>

</body>
</html>

myproject/blog/templates/blog/templates/techtips.html
<!DOCTYPE html>
<head>
	<title>Tech Tips</title>
{% load static %}
	<link href="{% static 'blog/static/style.css' %}" rel="stylesheet" title="Main style">

</head>



<body>
<header> THE BLOG
<nav>
	<a href="{% url 'blog:index' %}"> Home </a> |
	<a href="{% url 'blog:aboutme' %}"> About Me </a> |
	<a href="{% url 'blog:techtips' %}"> Tech Tips </a>|
        <a href="{% url 'blog:archive' %}"> Archive </a>
</nav>
</header>
<div  class="flex-box">
<main class="main">


<h1> Git Cheat Sheet </h1>
<p>I used the mozilla css guide for most of this. The images were marked for reuse</p>



<h2> Commit </h2>
<p>Use this command to commit (save) your changes:</p>
<p>
<code>git commit</code>
</p>

<h2>Log </h2>
<p> Use this command to view the history of commits with their messages: </p>
<p> <code> git log </code></p>

<h2>Add</h2>
<p> Use this command to tell git to track new documents. You can use --all to add all documents in the directory. </p>
<p><code>git add </code></p>

</main>

<aside class="aside">
<img src="{% static 'blog/static/nerd.png' %}" alt="Picture">
<img src="https://c1.staticflickr.com/4/3268/2909072284_cde1184f99_b.jpg" alt="Picture">
<img src="https://upload.wikimedia.org/wikipedia/commons/7/7f/William_Shatner_Star_Trek_first_episode_1966.JPG" alt="Picture">
</aside>

</div>
<footer>
Ryan Ferguson--{{ time }}
</footer>

</body>

myproject/polls/templates/index.html
{% if latest_question_list %}
	<ul>
	{% for question in latest_question_list %}
		<li><a href="{% url 'detail' question.id %}">{{ question.question_text }}</a></li>
	{% endfor %}
	</ul>
{%else%}
	<p>No polls are available</p>
{% endif %}

myproject/polls/templates/polls/detail.html
<DOCTYPE! HTML>
<head>
<title> Polls Detail View </title>
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}">


</head>
<body>
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{error_message }}</strong></p>{%endif%}

<form action="{% url 'polls:vote' question.id %}" method = "post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
	<label for="choice{{forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>
</body>

myproject/polls/templates/polls/index.html
<DOCTYPE! HTML>
<html>
<head>
<title>Polls App </title>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
</head>
<body>

{% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
                <li><a href = "{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
{% else %}
        <p>No polls are available.</p>
{% endif %}

</body>
</html>

myproject/polls/templates/polls/results.html
<DOCTYPE! HTML>
<head>
<title> Results View </title>
{% load static %}
<link rel="stylesheet" href="{% static 'polls/style.css' %}">
</head>

<body>
<h1>{{question.question_text}}</h1>

<ul>
{% for choice in question.choice_set.all %}
	<li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize}}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}"> Vote again?</a>
</body>